#!/bin/bash

. /etc/usbmount/usbmount.conf

if [ "$SHARESMB" = yes ]; then
        [ "$SHARELT" = yes ] && gst=N || gst=Y
        [ "$SHARERW" = yes ] && smbrw=Y || smbrw=N
        net conf addshare $(basename "$UM_MOUNTPOINT" | tr ' ' '_') "$UM_MOUNTPOINT" writeable=$smbrw guest_ok=$gst || :

        [ $gst = N ] && net conf setparm $(basename "$UM_MOUNTPOINT" | tr ' ' '_') "read list" xbian || :
        if [ $smbrw = Y ]; then
            net conf setparm $(basename "$UM_MOUNTPOINT" | tr ' ' '_') "write list" xbian || :
            net conf setparm $(basename "$UM_MOUNTPOINT" | tr ' ' '_') "force user" xbian || :
        fi
        net conf setparm $(basename "$UM_MOUNTPOINT" | tr ' ' '_') "browseable" yes || :
        net conf setparm $(basename "$UM_MOUNTPOINT" | tr ' ' '_') "comment" usbmount || :
fi
