#!/bin/bash

. /etc/usbmount/usbmount.conf

counter=0
while test -h $LINKDIR/usb$counter; do 
    [ "$(readlink -e $LINKDIR/usb$counter)" = "$UM_MOUNTPOINT" ] && exit 0
    counter=$(($counter + 1))
done

ln -s "$UM_MOUNTPOINT" $LINKDIR/usb$counter || exit 1

exit 0
